## Transform Using A Matrix

In [1]:
import torch
import torch.nn as nn

In [4]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6],
], dtype=torch.float32)

In [5]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

## Transform Using A PyTorch Linear Layer

In [7]:
fc = nn.Linear(in_features=4, out_features=3, bias=True)
fc(in_features)

tensor([ 2.0712, -0.7935,  0.6084], grad_fn=<AddBackward0>)

自定义Linear Layer的weight_matrix

In [9]:
fc.weight = nn.Parameter(weight_matrix)
fc(in_features)

tensor([29.9936, 39.7766, 49.5456], grad_fn=<AddBackward0>)

Turn off the bias of the linear layer

In [10]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)
fc.weight = nn.Parameter(weight_matrix)
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)