In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torchvision.transforms import transforms

In [3]:
train_set = torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ])
)

In [4]:
data_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size=10,
)

In [30]:
batch = next(iter(data_loader))
images, labels = batch

In [31]:
images.shape

torch.Size([10, 1, 28, 28])

In [32]:
labels.shape

torch.Size([10])

In [33]:
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120)
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
        
    def forward(self, t):
        t = t
        
        t = F.max_pool2d(F.relu(self.conv1(t)), kernel_size=2, stride=2)
        
        t = F.max_pool2d(F.relu(self.conv2(t)), kernel_size=2, stride=2)
        
        t = F.relu(self.fc1(t.reshape(-1, 12*4*4)))
        
        t = F.relu(self.fc2(t))
        
        t = self.out(t)
        
        return t

In [34]:
network = Network()
preds = network(images)

In [35]:
preds.shape

torch.Size([10, 10])

In [36]:
preds

tensor([[ 0.1493, -0.0791, -0.0562,  0.0520, -0.0892, -0.0395, -0.1254,  0.0568,
         -0.0418, -0.0539],
        [ 0.1524, -0.0793, -0.0592,  0.0494, -0.0906, -0.0281, -0.1202,  0.0511,
         -0.0380, -0.0544],
        [ 0.1513, -0.0915, -0.0559,  0.0490, -0.0795, -0.0291, -0.1060,  0.0686,
         -0.0218, -0.0707],
        [ 0.1511, -0.0849, -0.0568,  0.0485, -0.0824, -0.0320, -0.1122,  0.0638,
         -0.0321, -0.0665],
        [ 0.1583, -0.0787, -0.0573,  0.0454, -0.0922, -0.0347, -0.1231,  0.0530,
         -0.0359, -0.0580],
        [ 0.1443, -0.0802, -0.0567,  0.0464, -0.0796, -0.0293, -0.1152,  0.0563,
         -0.0323, -0.0597],
        [ 0.1449, -0.0841, -0.0553,  0.0426, -0.0692, -0.0309, -0.1155,  0.0586,
         -0.0332, -0.0618],
        [ 0.1458, -0.0814, -0.0550,  0.0499, -0.0809, -0.0305, -0.1094,  0.0578,
         -0.0297, -0.0617],
        [ 0.1476, -0.0842, -0.0548,  0.0526, -0.0716, -0.0331, -0.1165,  0.0659,
         -0.0257, -0.0643],
        [ 0.1500, -

In [37]:
preds.argmax(dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
labels

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [39]:
preds.argmax(dim=1).eq(labels)

tensor([False,  True,  True, False,  True, False, False, False, False, False])

## Correct predictions

In [40]:
preds.argmax(dim=1).eq(labels).sum()

tensor(3)

In [41]:
def get_num_correct(preds, labels):
    return preds.argmax(dim=1).eq(labels).sum().item()
get_num_correct(preds, labels)

3