Tensor Attributes：dtype, device and layout.

In [36]:
import torch
t = torch.Tensor()
type(t)
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


Creating Tensors with data.

In [14]:
import torch
import numpy as np
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [21]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)
print(o1)
print(o2)
print(o3)
print(o4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


Creating Tensors without data.

In [19]:
print(torch.eye(2))
print(torch.zeros([2,3]))
print(torch.ones([2,3]))
print(torch.rand([2,2]))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0150, 0.1529],
        [0.8887, 0.0463]])


Default dtype Vs Inferred dtype

In [24]:
print(torch.get_default_dtype())
print(o1.dtype)
print(o2.dtype)
print(o3.dtype)
print(o4.dtype)

torch.float32
torch.float32
torch.int64
torch.int64
torch.int64


Sharing Memory For Performance：Copy Vs Share

In [30]:
print('old:', data)
data [0] = 0
print('new:', data)

old: [1 2 3]
new: [0 2 3]


In [31]:
print(o1)
print(o2)
print(o3)
print(o4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 2, 3])
tensor([0, 2, 3])


You can call numpy() to convert the tensor to ndarray.

In [35]:
print(o3.numpy())
print(o4.numpy())

[0 2 3]
[0 2 3]
