# PyTorch Tensors
## Creating PyTorch Tensors for Deep Learning

In [16]:
import numpy as np
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [18]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [27]:
torch.tensor(data)

tensor([1, 2, 3])

In [28]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [49]:
torch.from_numpy(data)

tensor([0, 0, 0])

torch.Tensor()是Tensor类的Constructor，而其他三个是Tensor的Factories，即factory functions。

## Initial PyTorch Tensors

In [22]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [23]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [24]:
torch.ones(2,1)

tensor([[1.],
        [1.]])

In [25]:
torch.rand(2,2)

tensor([[0.8376, 0.1110],
        [0.5352, 0.9276]])

## Change dtype of PyTorch Tensors

In [32]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [34]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [35]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [39]:
 torch.get_default_dtype()

torch.float32

factories 的输出和输入的dtype一样，还能通过设置dtype参数设置，但constructor Tensor没有这一特性。

In [40]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [41]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory: Sharing vs Copying 

In [42]:
data = np.array([1,2,3])
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [43]:
data[0] = 0
data[1] = 0
data[2] = 0

In [44]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [46]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


可以发现，Tensor() 和 tensor() 是复制的内存，而as_tensor(),from_numpy()是和numpy array共享的内存。
因此，如果选择sharing memory，最好的选择是as_tensor()，因为他能接受包括numpy array的其他数据结构；而如果选择copying memory，那么最好的选择是tensor()

 # Tensor Operation

## Flatten, Reshape, and Squeeze

In [50]:
data = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
])

In [51]:
data.size()

torch.Size([3, 4])

In [52]:
data.shape

torch.Size([3, 4])

In [53]:
len(data.shape)

2

calculate the component of a tensor

In [54]:
torch.tensor(data.shape).prod()

tensor(12)

calculate the number of element of a tensor

In [57]:
data.numel()

12

reshape the tensor without changing the rank

In [58]:
data.reshape(4,3)

tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]])

In [59]:
data.reshape(6,2)

tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])

In [60]:
data.reshape(2,6)

tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]])

In [61]:
data.reshape(1,12)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [62]:
data.reshape(12,1)

tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]])

**squeeze** ：去掉tensor里长度为1的axis

In [63]:
print(data.reshape(1,12))
print(data.reshape(1,12).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


In [64]:
print(data.reshape(1,12).squeeze())
print(data.reshape(1,12).squeeze().shape)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])
torch.Size([12])


In [65]:
print(data.reshape(1,12).squeeze().unsqueeze(dim=0))
print(data.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


**flatten**：

In [66]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [67]:
flatten(data)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [68]:
data.reshape(1,12)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

## CNN Flatten Operation Visualized

In [69]:
t1 = torch.tensor([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
t2 = torch.tensor([
    [2,2,2],
    [2,2,2],
    [2,2,2],
])
t3 = torch.tensor([
    [3,3,3],
    [3,3,3],
    [3,3,3]
])

In [70]:
t = torch.stack((t1,t2,t3))

In [71]:
t

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]])

In [72]:
t.shape

torch.Size([3, 3, 3])

In [79]:
t = t.reshape(3,1,3,3)

In [80]:
# first image
t[0]

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [81]:
# first channel of first image
t[0][0]

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [82]:
# first hight of ...
t[0][0][0]

tensor([1, 1, 1])

In [83]:
t[0][0][0][0]

tensor(1)

以下做法flatten了所有的image

In [86]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [85]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [87]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [88]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

flatten each image with maintaining the batch axis: only flatten channel height and weight

In [89]:
t.flatten(start_dim=1).shape

torch.Size([3, 9])

In [90]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [92]:
t.reshape(3,9)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3]])

## Broadcasting And Element-wise Operation

In [95]:
 t1 = torch.tensor([
     [1,2],
     [3,4]
 ], dtype = torch.float32)

In [96]:
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype = torch.float32)

In [97]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [98]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [104]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [100]:
t1 *2

tensor([[2., 4.],
        [6., 8.]])

In [101]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [102]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [103]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [105]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [106]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [107]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [108]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [110]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape),
    dtype = torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

In [111]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype = torch.float32)

In [112]:
t2 = torch.tensor([1,2], dtype = torch.float32)

In [113]:
t1 + t2

tensor([[2., 3.],
        [2., 3.]])

In [114]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [115]:
t1 + t2

tensor([[2., 3.],
        [2., 3.]])

In [116]:
 t = torch.tensor([
     [0,5,7],
     [6,0,7],
     [0,8,0]
 ], dtype= torch.float32)

In [117]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [118]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [119]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [120]:
t.le(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [122]:
t.lt(7)

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True, False,  True]])

In [123]:
t < torch.tensor(
    np.broadcast_to(7, t.shape),
    dtype=torch.float32
)

tensor([[ True,  True, False],
        [ True,  True, False],
        [ True, False,  True]])

In [124]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [125]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [126]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [127]:
t.sqrt().neg()

tensor([[-0.0000, -2.2361, -2.6458],
        [-2.4495, -0.0000, -2.6458],
        [-0.0000, -2.8284, -0.0000]])

## Argmax and Reduction Ops

a reduction operation

In [2]:
import torch
import numpy as np

In [10]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

it's a scalar

In [4]:
t.sum()

tensor(8.)

In [11]:
t.numel()

9

In [12]:
t.sum().numel()

1

In [13]:
t.prod()

tensor(0.)

In [14]:
t.mean()

tensor(0.8889)

In [15]:
t.std()

tensor(1.1667)

In [16]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [17]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [18]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

t.sum(dim=0) 类似以下element-wisw操作

In [19]:
t[0]

tensor([1., 1., 1., 1.])

In [20]:
t[1]

tensor([2., 2., 2., 2.])

In [21]:
t[2]

tensor([3., 3., 3., 3.])

In [22]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

t.sum(dim=1)

In [24]:
t[0].sum()

tensor(4.)

In [25]:
t[1].sum()

tensor(8.)

In [26]:
t[2].sum()

tensor(12.)

Argmax tensor reduction op: tell the index location of the maxumum value inside a tensor

In [27]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
],dtype=torch.float32)

In [28]:
t.max()

tensor(5.)

In [29]:
t.argmax()

tensor(11)

In [30]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [31]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [32]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [33]:
t.max(1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [34]:
t.argmax(dim=1)

tensor([3, 2, 3])

In [35]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [37]:
t.mean()

tensor(5.)

In [38]:
t.mean().item()

5.0

In [39]:
t.mean(dim=0)

tensor([4., 5., 6.])

In [40]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [41]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)