In [1]:
import torch
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

## Common Reduction Ops

In [2]:
t.sum()

tensor(8.)

In [3]:
t.numel()

9

In [4]:
t.prod()

tensor(0.)

In [5]:
t.mean()

tensor(0.8889)

In [6]:
t.std()

tensor(1.1667)

## Reduction Tensors By Axes

In [7]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [8]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [9]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [10]:
t.mean(dim=0)

tensor([2., 2., 2., 2.])

## Argmax

In [11]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [12]:
t.max()

tensor(5.)

In [14]:
print(t.flatten())
t.argmax()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])


tensor(11)

In [15]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [16]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [17]:
t.argmax(dim=1)

tensor([3, 2, 3])

## Accessing Elements Inside Tensors

In [19]:
import torch
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [20]:
t.mean().item()

5.0

Access multple values

In [21]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [22]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)