In [1]:
import torch
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

## Addition

In [2]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

## Arithmetic Operations

In [11]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [16]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [6]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [7]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

## Build-in methods

In [18]:
print(t1.add(2))
print(t1.sub(2))
print(t1.mul(2))
print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


## Broadcasting Tensors

In [20]:
import numpy as np
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [23]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)
t2 = torch.tensor([2,4], dtype=torch.float32)
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [36]:
np.broadcast_to(t2, t1.shape)

array([[5, 5, 5]])

### Same Shapes

In [33]:
t1 = torch.tensor([
    [1,2,3]
])
print(t1.shape)
t2 = torch.tensor([
    [4,5,6]
])
print(t2.shape)
t1 + t2

torch.Size([1, 3])
torch.Size([1, 3])


tensor([[5, 7, 9]])

### Same Rank, Different Shapes

In [32]:
t1 = torch.tensor([
    [1,2,3]
])
print(t1.shape)
t2 = torch.tensor([
    [4],
    [5],
    [6]
])
print(t2.shape)
t1 + t2

torch.Size([1, 3])
torch.Size([3, 1])


tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

### Different Ranks

In [35]:
t1 = torch.tensor([
    [1,2,3]
])
print(t1.shape)
t2 = torch.tensor(5)
print(t2.shape)
t1 + t2

torch.Size([1, 3])
torch.Size([])


tensor([[6, 7, 8]])

## Comparison Operation

In [37]:
torch.tensor([1,2,3]) < torch.tensor([3,1,2])

tensor([ True, False, False])

In [38]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [39]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [40]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [41]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [42]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [43]:
t.le(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

## Using Fuctions

In [44]:
t.abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [45]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [46]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])