In [3]:
import torch
import numpy as np
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t.size())
print(t.shape)

torch.Size([3, 4])
torch.Size([3, 4])


# Reshape

In [4]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [6]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [7]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [8]:
t.reshape([6,2])

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [9]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [11]:
t.view(3,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

## Squeeze And Unsqueeze

In [13]:
print(t.reshape([1,12]))
t.reshape([1,12]).shape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])


torch.Size([1, 12])

In [16]:
print(t.reshape([1,12]).squeeze())
t.reshape([1,12]).squeeze().shape

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


torch.Size([12])

In [18]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
t.reshape(1,12).squeeze().unsqueeze(dim=0).shape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])


torch.Size([1, 12])

## Concatenating Tensors

In [24]:
import torch
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])
t3 = torch.tensor([
    [9,10],
    [11,12]
])

row-wise

In [25]:
torch.cat((t1,t2,t3), dim=0)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

column-wise

In [26]:
torch.cat((t1,t2,t3),dim=1)

tensor([[ 1,  2,  5,  6,  9, 10],
        [ 3,  4,  7,  8, 11, 12]])

## Flatten

three 4*4 images, tensor:[3,1,4,4]

In [31]:
import torch
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])
# the stack() method to concatenate our sequence of three tensors along a new axis
# default new axis is dim 0
t = torch.stack((t1,t2,t3))
t.shape
t.reshape(3,1,4,4)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

flatten all axes

In [41]:
print(t.reshape(1, -1)[0])
print(t.reshape(-1))
print(t.view(t.numel()))
print(t.flatten())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])


flatten part of axes: (C, H, W)

In [43]:
print(t.flatten(start_dim=1))
t.flatten(start_dim=1).shape

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


torch.Size([3, 16])

Flatten an RGB Image

In [46]:
import torch
r = torch.ones(1,2,2)
g = torch.ones(1,2,2) + 1
b = torch.ones(1,2,2) + 2
img = torch.cat(
    (r,g,b),
    dim=0
)
img.shape

torch.Size([3, 2, 2])

In [49]:
print(img.flatten(start_dim=1))


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])
