In [3]:
import torch
import numpy as np
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t.size())
print(t.shape)

torch.Size([3, 4])
torch.Size([3, 4])


Reshape

In [4]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [6]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [7]:
t.reshape([4,3])

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [8]:
t.reshape([6,2])

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [9]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [11]:
t.view(3,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])

Squeeze And Unsqueeze

In [13]:
print(t.reshape([1,12]))
t.reshape([1,12]).shape

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])


torch.Size([1, 12])

In [16]:
print(t.reshape([1,12]).squeeze())
t.reshape([1,12]).squeeze().shape

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


torch.Size([12])

In [17]:
print(t.reshape(1,12).squeeze().unsqeeze(dim=0))
t.reshape(1,12).squeeze().unsqueeze(dim=0).shape

AttributeError: 'Tensor' object has no attribute 'unsqeeze'